package settings

import (
	"context"
	"path/filepath"
	"testing"

	"github.com/OnyxAxisOwO/ObsidianArc/internal/config"
	"github.com/OnyxAxisOwO/ObsidianArc/internal/database"
)

func TestDetectLogoMedia(t *testing.T) {
	cases := []struct {
		name string
		data []byte
		want string
		err  bool
	}{
		{
			name: "png",
			data: []byte("\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR"),
			want: "image/png",
		},
		{
			name: "jpeg",
			data: []byte("\xFF\xD8\xFF\xE0\x00\x10JFIF\x00\x01"),
			want: "image/jpeg",
		},
		{
			name: "gif",
			data: []byte("GIF89a\x01\x00\x01\x00"),
			want: "image/gif",
		},
		{
			name: "webp",
			data: []byte("RIFF\x00\x00\x00\x00WEBPVP8 "),
			want: "image/webp",
		},
		{
			name: "ico",
			data: []byte("\x00\x00\x01\x00\x01\x00\x10\x10"),
			want: "image/x-icon",
		},
		{
			name: "svg standard",
			data: []byte("<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><circle cx='50' cy='50' r='40'/></svg>"),
			want: "image/svg+xml",
		},
		{
			name: "svg with xml declaration",
			data: []byte("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg viewBox=\"0 0 24 24\"></svg>"),
			want: "image/svg+xml",
		},
		{
			name: "svg with utf8 bom",
			data: append([]byte("\xef\xbb\xbf"), []byte("<svg viewBox=\"0 0 24 24\"></svg>")...),
			want: "image/svg+xml",
		},
		{
			name: "svg with comment and doctype",
			data: []byte("<!-- Generated by app -->\n<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\" \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\n<svg width=\"100\"></svg>"),
			want: "image/svg+xml",
		},
		{
			name: "invalid text",
			data: []byte("hello world not an image"),
			err:  true,
		},
		{
			name: "too short",
			data: []byte("a"),
			err:  true,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, err := DetectLogoMedia(tc.data)
			if tc.err {
				if err == nil {
					t.Fatalf("expected error, got %s", got)
				}
				return
			}
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if got != tc.want {
				t.Fatalf("DetectLogoMedia() = %q, want %q", got, tc.want)
			}
		})
	}
}

func TestSiteLogoCRUD(t *testing.T) {
	ctx := t.Context()
	db, err := database.Open(ctx, config.Database{
		Driver: "sqlite", DSN: filepath.Join(t.TempDir(), "settings_logo.db"),
	})
	if err != nil {
		t.Fatalf("open db: %v", err)
	}
	defer db.Close()

	if _, err := db.Migrate(ctx); err != nil {
		t.Fatalf("migrate: %v", err)
	}

	svc := New(db)
	if err := svc.Load(ctx); err != nil {
		t.Fatalf("load: %v", err)
	}

	if svc.SiteLogoUpdatedAt() != 0 {
		t.Fatalf("expected 0 initially, got %d", svc.SiteLogoUpdatedAt())
	}

	// Read when empty -> ErrNoLogo
	_, _, _, err = svc.GetSiteLogo(ctx)
	if err != ErrNoLogo {
		t.Fatalf("expected ErrNoLogo, got %v", err)
	}

	// Set logo
	pngData := []byte("\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01\x08\x06\x00\x00\x00\x1f\x15\xc4\x89")
	at, err := svc.SetSiteLogo(ctx, "image/png", pngData)
	if err != nil {
		t.Fatalf("set logo: %v", err)
	}
	if at == 0 || svc.SiteLogoUpdatedAt() != at {
		t.Fatalf("expected timestamp %d, got %d", at, svc.SiteLogoUpdatedAt())
	}

	// Read logo back
	mime, data, readAt, err := svc.GetSiteLogo(ctx)
	if err != nil {
		t.Fatalf("get logo: %v", err)
	}
	if mime != "image/png" {
		t.Fatalf("expected image/png, got %s", mime)
	}
	if string(data) != string(pngData) {
		t.Fatalf("data mismatch")
	}
	if readAt != at {
		t.Fatalf("timestamp mismatch: %d != %d", readAt, at)
	}

	// Reload in fresh service -> should retain siteLogoAt
	fresh := New(db)
	if err := fresh.Load(ctx); err != nil {
		t.Fatalf("reload fresh: %v", err)
	}
	if fresh.SiteLogoUpdatedAt() != at {
		t.Fatalf("expected fresh siteLogoAt = %d, got %d", at, fresh.SiteLogoUpdatedAt())
	}

	// Delete logo
	if err := svc.DeleteSiteLogo(ctx); err != nil {
		t.Fatalf("delete logo: %v", err)
	}
	if svc.SiteLogoUpdatedAt() != 0 {
		t.Fatalf("expected 0 after delete, got %d", svc.SiteLogoUpdatedAt())
	}
	_, _, _, err = svc.GetSiteLogo(context.Background())
	if err != ErrNoLogo {
		t.Fatalf("expected ErrNoLogo after delete, got %v", err)
	}
}
